responsavel = input("Digite o nome o nome do responsável: ")
funcionario = input("Digite o nome do funcionário: ")
evento = input("Digite o nome do evento: ")
entrada = float(input("Digite o valor gasto: "))
print("Declaro para o senhor " + responsavel + " que o senhor " + funcionario + " esteve presente no evento " + evento + " e gastou o valor de R$ " +str(entrada) + " com a entrada.")
